baseurl: ''
permalink: pretty
title: 'NutrEpiWeb'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "assets/images/logo/logo-mobile.svg"
  desktop: "assets/images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Powered by <a class="zerostatic" href="https://github.com/zerostaticthemes/jekyll-serif-theme">Jekyll Serif Theme</a> (<a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>)'

seo:
  meta_og_title: "NutrEpiWeb"
  meta_og_type: "website"
  meta_og_url: "https://nutrepi.github.io/"
  meta_og_description: "NutrEpiWeb is a portal website for linking all the NutrEpi project websites."

url: "https://nutrepi.github.io" # the base hostname & protocol for your site

collections:
  workpackages:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .travis.yml
  - stackbit.yaml
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - README.md
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
  - /scripts
  - /data
  - Gemfile_macos.lock
  - Gemfile_linux.lock
  - Gemfile_linux_macos.lock
