baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'NutrEpiWeb'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Powered by <a class="zerostatic" href="https://github.com/zerostaticthemes/jekyll-serif-theme">Jekyll Serif Theme</a> (<a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>)'

seo:
  meta_og_title: "NutrEpiWeb"
  meta_og_type: "website"
  meta_og_url: "https://nutrepi.github.io/"
  meta_og_description: "NutrEpiWeb is a hub website with the links for all the NutrEpi projects."

collections:
  services:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
